{{- $component := "api" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secret
  labels:
    {{- include "d3d-stack.componentLabels" (dict "root" . "component" $component) | nindent 4 }}
type: Opaque
stringData:
  signing_key: {{ .Values.api.config.signingKey | quote }}
