{{- if .Values.rethinkdb.webUI.enabled -}}
{{- $component := "rethinkdb" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rethinkdb-ui
  labels:
    {{- include "d3d-stack.componentLabels" (dict "root" . "component" $component) | nindent 4 }}
    app.kubernetes.io/role: web-ui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    {{- include "d3d-stack.componentSelector" (dict "root" . "component" $component) | nindent 4 }}
{{- end }}
